# Generated by Django 4.1.5 on 2023-06-04 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenumber', models.CharField(max_length=14)),
                ('memberfirstname', models.CharField(max_length=35, verbose_name='Фамилия')),
                ('memberlastname', models.CharField(max_length=35, verbose_name='Имя')),
                ('memberfathername', models.CharField(max_length=35, verbose_name='Отчество')),
                ('memberbirthday', models.DateField(verbose_name='Дата рождения')),
                ('social', models.CharField(choices=[('W', 'Трудоспособный'), ('P', 'Пенсионер'), ('D', 'Инвалид')], max_length=1, verbose_name='Социальный статус')),
                ('relation', models.CharField(choices=[('W', 'Жена/Муж'), ('M', 'Мать/Отец'), ('C', 'Гражданская жена'), ('S', 'Сын/Дочь')], max_length=1, verbose_name='Семейный статус')),
                ('memberotherdata', models.CharField(max_length=100, verbose_name='Примечание')),
                ('building', models.CharField(max_length=10, verbose_name='Номер дома')),
                ('apartment', models.IntegerField(verbose_name='Номер квартиры')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobilization.city', verbose_name='Название населенного пункта')),
            ],
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Needs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('needname', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=35, verbose_name='Фамилия')),
                ('lastname', models.CharField(max_length=35, verbose_name='Имя')),
                ('fathername', models.CharField(max_length=35, verbose_name='Отчество')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('status', models.CharField(choices=[('M', 'Мобилизованный'), ('W', 'Военнослужащий'), ('D', 'Погибший'), ('C', 'Комиссованный'), ('L', 'Пропавший без вести')], max_length=1, verbose_name='Статус военнослужащего')),
                ('statusdate', models.DateField(verbose_name='Дата получения статуса')),
                ('otherdata', models.CharField(max_length=100, verbose_name='Примечание')),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('date', models.DateField()),
                ('expiredate', models.DateField()),
                ('reportdate', models.DateField()),
                ('complete', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobilization.familymember')),
                ('need', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobilization.needs')),
            ],
        ),
        migrations.AddField(
            model_name='needs',
            name='memberid',
            field=models.ManyToManyField(through='mobilization.Protocol', to='mobilization.familymember'),
        ),
        migrations.AddField(
            model_name='familymember',
            name='index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobilization.index', verbose_name='Почтовый индекс'),
        ),
        migrations.AddField(
            model_name='familymember',
            name='mobilized',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobilization.person'),
        ),
        migrations.AddField(
            model_name='familymember',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobilization.street', verbose_name='Улица'),
        ),
    ]
